services:
    # Forms   
    asf_commerce.form.factory.cart:
        class: ASF\CommerceBundle\Form\Factory\FormFactory
        arguments: ["@form.factory", "%asf_commerce.cart.form.name%", "%asf_commerce.cart.form.type%", "%asf_commerce.cart.entity%"]
        
    asf_commerce.form.type.cart:
        class: ASF\CommerceBundle\Form\Type\CartType
        tags:
            - { name: form.type, alias: cart_type }
            