services:
    # Forms   
    asf_commerce.form.factory.discount:
        class: ASF\CommerceBundle\Form\Factory\FormFactory
        arguments: ["@form.factory", "%asf_commerce.discount.form.name%", "%asf_commerce.discount.form.type%", "%asf_commerce.discount.entity%"]
        
    asf_commerce.form.type.discount:
        class: ASF\CommerceBundle\Form\Type\DiscountType
        tags:
            - { name: form.type, alias: discount_type }

    asf_commerce.form.type.discount_collection:
        class: ASF\CommerceBundle\Form\Type\DiscountCollectionType
        arguments: ["%asf_commerce.discount.entity%"]
        tags:
            - { name: form.type, alias: discount_collection_type }
