services:
    # Form   
    asf_commerce.form.factory.tax:
        class: ASF\CommerceBundle\Form\Factory\FormFactory
        arguments: ["@form.factory", "%asf_commerce.tax.form.name%", "%asf_commerce.tax.form.type%", "%asf_commerce.tax.entity%"]
        
    asf_commerce.form.type.tax:
        class: ASF\CommerceBundle\Form\Type\TaxType
        tags:
            - { name: form.type, alias: tax_type }

